### ISSUE TITLE
Variable Redeclaration

### ISSUE THREAD

**Issue by adam-r-kowalski** [jedwards1211/meteor-webpack-react#29]
Hey I just wanted to say that this is an awesome repo and I really appreciate what you guys have done here. However, I did have a couple of questions about the webpack code you guys have setup.

```js
// webpack.config.client.dev.js
var webpack = require('webpack');
var config = require('./webpack.config.client');
var _ = require('lodash');

var devProps = require('./devProps');

var config = module.exports = _.assign(_.cloneDeep(config), {
...
```

```js
// webpack.config.client.prod.js
var webpack = require('webpack');
var config = require('./webpack.config.client');
var _ = require('lodash');

var config = module.exports = _.assign(_.cloneDeep(config), {
...
```

```js
// webpack.config.server.prod.js
var webpack = require('webpack');
var config = require('./webpack.config.server');
var _ = require('lodash');

var config = module.exports = _.assign(_.cloneDeep(config), {
...
```

You guys seem to have defined config twice? Is this intentional? I think that it might make sense to either just drop the var and just redefine it or use a different variable name on one place.

Also I am using no-ip to setup a quick public url I can access my app from and I am also running into another problem there. When I run the ./dev script I get all the awesome benefits of hot reloading and webpack but it only works on localhost.

if I want to check how the site looks on another device (ie: my phone) I generally use my public ip address. I then need to use the ./prod build as that seems to be the only version that works with non localhost addresses. I tried changing any instance I saw of localhost:3000 to 0.0.0.0:3000 but that didn't seem to do the trick. Can you guys point me in the right direction as to what I need to change to get everything set up?

**Comment by grigio** [comment]
config = config + environment-specific-stuff so it is redefined later, yep the second var isn't needed because config is already there.

on the second part it should work now, however it works with these changes https://github.com/jedwards1211/meteor-webpack-react/pull/25/files

**Comment by jedwards1211** [comment]
@grigio @adam-r-kowalski redefining `config`

**Comment by jedwards1211** [comment]
The wifi I'm using right now doesn't seem to allow connections between my devices, so I can't test till later, but I see that meteor says it's running at `localhost:3000`.  If I put `meteor --host 0.0.0.0:3000`, it says it's running at `0.0.0.0:3000`.  But as far as I understand it should be listening on all interfaces by default: https://github.com/meteor/meteor/issues/159

**Comment by grigio** [comment]
I don't know i'm still using an old version of this project.
meteor listens on all interfaces by default, so the unique fix is for webpack-dev-server

**Comment by adam-r-kowalski** [comment]
I just cloned the local-net branch and tried running the ./dev command but I still get the same problem.

```
Failed to load resource: net::ERR_CONNECTION_REFUSED 
http://my-public-ip:9090/assets/client.bundle.js
```

**Comment by jedwards1211** [comment]
Ah, cool, I'm glad, because I just tested and I can't reproduce :)

**Comment by jedwards1211** [comment]
@adam-r-kowalski I added a note about port-forwarding to the README.  Thanks for figuring this out!
