### ISSUE TITLE
hot reloading sometimes fails because server doesn't provide CORS header

### ISSUE THREAD

**Issue by jedwards1211** [jedwards1211/meteor-webpack-react#45]
I've seen this at least once, though I haven't thoroughly investigated why it doesn't always fail...

I think the eventual solution may be to:
* use `webpack-dev-middleware`
* add an index route that:
  * requests the meteor page from `localhost:3000`
  * injects the bundles into the HTML (I also want to make it inject a React commons bundle in the right place so that the fork of `react-packages` can use it)
  * serves it up

That approach may interfere with automatic app caching via whatever that Meteor package for app caching is, I don't know.  It would be so much better if you could get Meteor to put handwritten `<script>` tags in a specific order in the `<head>` though...

**Comment by rclai** [comment]
I don't know if this is related but I've noticed that component hot reloading works, but when I intentionally make a syntax error, I expect that red error overlay to show up but it doesn't, however, I do get the error message on the console, but in addition I get this error:

```
XMLHttpRequest cannot load http://0.0.0.0:9090/assets/bcc6879b58ecc788f291.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
only-dev-server.js:21 [HMR] Update check failed: Error: Manifest request to http://0.0.0.0:9090/assets/bcc6879b58ecc788f291.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://0.0.0.0:9090/assets/client.bundle.js:34:23)
```

**Comment by rclai** [comment]
Oh I just found out that the error overlay doesn't show up for specific kinds of errors. If I do a syntax error, the error reporter will break, but if I do a reference not found error, it works properly.

**Comment by AdamBrodzinski** [comment]
@rclai Yea i'm getting that too. I think that's the expected outcome... I believe the app has to compile before redbox can 'catch' any error that's thrown at runtime.

**Comment by rclai** [comment]
I also noticed that if that error comes up, hot loading doesn't work properly afterwards. I have to refresh the page in order to get it back to normal.

I noticed that @eXon's kickstarter doesn't have this problem. I haven't looked into why, yet.

**Comment by jedwards1211** [comment]
Hmmm, I know that if an error prevents even the initial React render from working, later changes won't hot load because React.render() won't get called again.  I know that in the gif for `react-transform` they used some extra thing to display the compile error messages in the browser, maybe we could use that.

**Comment by jedwards1211** [comment]
In any case it would be an improvement to make it serve everything through the same port so that we never get those CORS errors.

**Comment by jedwards1211** [comment]
And now that I think about it, I think that having a little Express JS server or whatever instead of Bash scripts is definitely the more modern, seamless way to go

**Comment by rclai** [comment]
That's what [this package](https://github.com/thereactivestack/meteor-webpack-hot-reload) does. I think that's how @eXon was able to get it to work.

**Comment by eXon** [comment]
@rclai It could be possible to implement this plugin in this project. You can check the readme but the kickstarter is a good example.

**Comment by jedwards1211** [comment]
Right, I've read your code :)

I want to use `webpack` on the server side as well.  I'm wondering if it's possible to create a source handler for webpack config files that calls `webpack` in watch mode.  That way the server side webpack would be seamlessly invoked when you run `meteor`.

**Comment by jedwards1211** [comment]
@rclai eXon's project doesn't have the problem because it uses `webpack-dev-middleware` to serve up its files over the Meteor port, rather than running `webpack-dev-server` separately.

**Comment by rclai** [comment]
That makes sense.

I tried integrating that package into this setup, but couldn't get it to work. Webpack's insane..

**Comment by jedwards1211** [comment]
Huh, what issue did you run into?  It would take a bit of work to integrate the two projects' approaches, but I want to do it once I have some spare time.  Yeah, Webpack is a beast but I'm assuming it will continue to be useful for a long time (I'm wondering, when browsers finally support ES6, how will they fetch hundreds of separate JS files efficiently?)

**Comment by rclai** [comment]
Oh what I meant that I couldn't massage the webpack configuration to play with the `webpack:hot-reload` package. I tried deleting some lines of bash code and from the config to let the middleware server do its thing but failed.

**Comment by jedwards1211** [comment]
I'm sure it can be done, it will probably just take some time.
In any case, I want to see if I can make a Meteor package that just creates a source handler for webpack config files.  That way webpack bundles could be used on the server, and it would be a little easier to manage multiple webpack configs/multiple output bundles than with `webpack:hot-reload`.

**Comment by eXon** [comment]
@jedwards1211 If you would like to improve `webpack:hot-reload` to support different webpack configs, you're welcome to do a PR. Their is a lot of improvements I'm working on right now.

**Comment by rclai** [comment]
Oh snap, a custom source handler would be really awesome!

**Comment by jedwards1211** [comment]
@eXon I'd be happy to eventually, so you'd like for `webpack:hot-reload` to have a source handler option as well?

**Comment by jedwards1211** [comment]
@eXon I think your approach is more robust, so I'd rather contribute to it in the long run.  Do you have any interest in using webpack to make bundles for the server side in that project?
Also I think you'll need to fix the core-js `Number` constructor conflicting with Meteor `check` in that project at some point.

**Comment by jedwards1211** [comment]
@eXon actually I forget, my boss wants me to release tools under our GitHub organization as a form of promotion, and what I'm talking about is a pretty large, orthogonal way of using webpack, so if I implement it I'll release it under my boss' project.

**Comment by jedwards1211** [comment]
I just realized something.  If the kickstart project runs `webpack-dev-middleware` from the Meteor server, doesn't that mean it has to rebuild the client bundle(s) each time the server restarts?  If that's the case, that's not the direction I want to take this project, because when I'm doing full-stack development, it's pretty common to change the server code.

**Comment by jedwards1211** [comment]
I tried out the custom source handler approach.  It does work for dev server bundles and I was even able to make it automatically load the output bundle(s) into the browser, so that you don't even have to use a config variable to specify which bundle to load (plus an arbitrary number of bundles is supported).  

However, despite valiant hacks I tried to use webpack bundles on the server side via a source handler, I still haven't figured out how to work around some of isobuild's severe limitations.

Unfortunately a smart source handler for client side bundles wasn't clean either -- I had to rely on the deprecated CompileStep API because the new build plugin API refuses to provide full absolute paths to files, which is what I needed to `require` the `webpack.config.js` files.

**Comment by jedwards1211** [comment]
Turns out there is a `crossOriginLoading` option for Webpack now.  I added that to the client dev config.  Though I haven't figured out exactly when I get the CORS errors, so I haven't figure out how to test that the issue is fixed yet

**Comment by AdamBrodzinski** [comment]
> doesn't that mean it has to rebuild the client bundle(s) each time the server restarts? 

Not sure if this is still an issue... you can use a hack with the folder name: `.#foo/` and it won't reload on every change. However I think the leading dot will make the packager skip bundling it? I used that for generating PDF files so i'm not sure about bundled JS.

**Comment by jedwards1211** [comment]
@AdamBrodzinski I think you thought I was talking about this project, I was talking about with Benoit's project

**Comment by jbbr** [comment]
I also got these CORS errors from time to time and was able to reproduce them:

1. Use hot reload with an React component: Works everytime if you don't introduce syntax errors
    e.g. change `<b>hello world</b>` to `<i>hello world</i>`

2. Add a JSX syntax error (not just JS undefined error)
    e.g `<i>hello world</i>` to `<>hello world</>`
    => Access control error / CORS, Access to 0.0.0.0:9090 denied

3. Now hot reload fails...

This problem still exists with `crossOriginLoading: 'anonymous'`
So I did some investigation and found the "headers" option for the webpack-dev-server.
I added it like this:

```js
devServer: {
    publicPath: devPr.....,
    .....
    headers: { "Access-Control-Allow-Origin": "*" },
  }
```

Now the cross origin error changed: Access denied to 0.0.0.0:3000 (access from 0.0.0.0:9090)
Okay, let's set some headers for Meteor server:

```js
// file: meteor_core/server/cors.js
WebApp.connectHandlers.use(function(req, res, next) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  return next();
});
```

Result: No more CORS errors. But: hot reload is still broken after adding JSX syntax errors...

**Comment by rclai** [comment]
I am also still getting the CORS error even after adding that new `crossOriginLoading`.

**Comment by jedwards1211** [comment]
Yep.  Good work @jbbr, that at least gets us closer...probably now we just need that tool that allows reloading when the initial `ReactDOM.render` call failed to mount anything because of syntax errors in the components.

**Comment by jedwards1211** [comment]
Huh.  Using iframe mode (http://localhost:9090/webpack-dev-server/index.html) appears to work, at least with the CORS headers set up on the Meteor server!

**Comment by jedwards1211** [comment]
And it appears to have built-in support for recovering from compilation errors!

**Comment by jedwards1211** [comment]
I was hoping with iframe mode it wouldn't be necessary for the script link to use port 9090...but unfortunately it is still necessary

**Comment by jedwards1211** [comment]
Oh duh...it works so well because the root page can have a websocket connection to the dev server, and the iframe can have a websocket connection to meteor.

**Comment by rclai** [comment]
So has this been resolved completely or are there some cases that this doesn't work properly?

**Comment by jedwards1211** [comment]
Not really...iframe mode has its downsides, for instance your actual page isn't connected with the URL bar.  I still haven't verified if the following means Meteor's not using a WebSocket at all when proxying:

WebSocket connection to 'ws://0.0.0.0:9090/sockjs/154/timeznho/websocket' failed: Connection closed before receiving a handshake response

**Comment by grigio** [comment]
is there a workaround for this?

**Comment by jedwards1211** [comment]
This is fixed in the [1.1.1 release](https://github.com/jedwards1211/meteor-webpack-react/releases/tag/1.1.1)

**Comment by rclai** [comment]
Cool!
